namespace Spriteman
{
	public partial class ColorEditDialog : global::System.Windows.Forms.Form
	{
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}
		private void InitializeComponent()
		{
			this.alphaBar = new global::System.Windows.Forms.TrackBar();
			this.label1 = new global::System.Windows.Forms.Label();
			this.saveButton = new global::System.Windows.Forms.Button();
			this.alphaBox = new global::System.Windows.Forms.NumericUpDown();
			this.newPreviewBox = new global::System.Windows.Forms.PictureBox();
			this.origPreviewBox = new global::System.Windows.Forms.PictureBox();
			this.cancelButton = new global::System.Windows.Forms.Button();
			this.redBox = new global::System.Windows.Forms.NumericUpDown();
			this.label2 = new global::System.Windows.Forms.Label();
			this.redBar = new global::System.Windows.Forms.TrackBar();
			this.greenBox = new global::System.Windows.Forms.NumericUpDown();
			this.label3 = new global::System.Windows.Forms.Label();
			this.greenBar = new global::System.Windows.Forms.TrackBar();
			this.blueBox = new global::System.Windows.Forms.NumericUpDown();
			this.label4 = new global::System.Windows.Forms.Label();
			this.blueBar = new global::System.Windows.Forms.TrackBar();
			this.label5 = new global::System.Windows.Forms.Label();
			this.hexBox = new global::System.Windows.Forms.TextBox();
			((global::System.ComponentModel.ISupportInitialize)this.alphaBar).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.alphaBox).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.newPreviewBox).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.origPreviewBox).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.redBox).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.redBar).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.greenBox).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.greenBar).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.blueBox).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.blueBar).BeginInit();
			base.SuspendLayout();
			this.alphaBar.LargeChange = 8;
			this.alphaBar.Location = new global::System.Drawing.Point(55, 271);
			this.alphaBar.Maximum = 255;
			this.alphaBar.Name = "alphaBar";
			this.alphaBar.Size = new global::System.Drawing.Size(260, 45);
			this.alphaBar.TabIndex = 0;
			this.alphaBar.TickFrequency = 8;
			this.alphaBar.Value = 255;
			this.alphaBar.Scroll += new global::System.EventHandler(this.alphaBar_Scroll);
			this.label1.AutoSize = true;
			this.label1.Location = new global::System.Drawing.Point(12, 276);
			this.label1.Name = "label1";
			this.label1.Size = new global::System.Drawing.Size(37, 13);
			this.label1.TabIndex = 1;
			this.label1.Text = "Alpha:";
			this.label1.TextAlign = global::System.Drawing.ContentAlignment.TopRight;
			this.saveButton.Location = new global::System.Drawing.Point(240, 322);
			this.saveButton.Name = "saveButton";
			this.saveButton.Size = new global::System.Drawing.Size(60, 23);
			this.saveButton.TabIndex = 2;
			this.saveButton.Text = "Save";
			this.saveButton.UseVisualStyleBackColor = true;
			this.saveButton.Click += new global::System.EventHandler(this.saveButton_Click);
			this.alphaBox.Location = new global::System.Drawing.Point(321, 274);
			global::System.Windows.Forms.NumericUpDown numericUpDown = this.alphaBox;
			int[] array = new int[4];
			array[0] = 255;
			numericUpDown.Maximum = new decimal(array);
			this.alphaBox.Name = "alphaBox";
			this.alphaBox.Size = new global::System.Drawing.Size(45, 20);
			this.alphaBox.TabIndex = 3;
			global::System.Windows.Forms.NumericUpDown numericUpDown2 = this.alphaBox;
			int[] array2 = new int[4];
			array2[0] = 255;
			numericUpDown2.Value = new decimal(array2);
			this.alphaBox.ValueChanged += new global::System.EventHandler(this.alphaBox_ValueChanged);
			this.newPreviewBox.BackgroundImage = global::Spriteman.Properties.Resources.check;
			this.newPreviewBox.Location = new global::System.Drawing.Point(183, 12);
			this.newPreviewBox.Name = "newPreviewBox";
			this.newPreviewBox.Size = new global::System.Drawing.Size(128, 100);
			this.newPreviewBox.TabIndex = 5;
			this.newPreviewBox.TabStop = false;
			this.newPreviewBox.Paint += new global::System.Windows.Forms.PaintEventHandler(this.newPreviewBox_Paint);
			this.origPreviewBox.BackgroundImage = global::Spriteman.Properties.Resources.check;
			this.origPreviewBox.Location = new global::System.Drawing.Point(55, 12);
			this.origPreviewBox.Name = "origPreviewBox";
			this.origPreviewBox.Size = new global::System.Drawing.Size(128, 100);
			this.origPreviewBox.TabIndex = 4;
			this.origPreviewBox.TabStop = false;
			this.origPreviewBox.Paint += new global::System.Windows.Forms.PaintEventHandler(this.origPreviewBox_Paint);
			this.cancelButton.Location = new global::System.Drawing.Point(306, 322);
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.Size = new global::System.Drawing.Size(60, 23);
			this.cancelButton.TabIndex = 6;
			this.cancelButton.Text = "Cancel";
			this.cancelButton.UseVisualStyleBackColor = true;
			this.cancelButton.Click += new global::System.EventHandler(this.cancelButton_Click);
			this.redBox.Location = new global::System.Drawing.Point(321, 121);
			global::System.Windows.Forms.NumericUpDown numericUpDown3 = this.redBox;
			int[] array3 = new int[4];
			array3[0] = 255;
			numericUpDown3.Maximum = new decimal(array3);
			this.redBox.Name = "redBox";
			this.redBox.Size = new global::System.Drawing.Size(45, 20);
			this.redBox.TabIndex = 9;
			global::System.Windows.Forms.NumericUpDown numericUpDown4 = this.redBox;
			int[] array4 = new int[4];
			array4[0] = 255;
			numericUpDown4.Value = new decimal(array4);
			this.redBox.ValueChanged += new global::System.EventHandler(this.redBox_ValueChanged);
			this.label2.AutoSize = true;
			this.label2.Location = new global::System.Drawing.Point(19, 123);
			this.label2.Name = "label2";
			this.label2.Size = new global::System.Drawing.Size(30, 13);
			this.label2.TabIndex = 8;
			this.label2.Text = "Red:";
			this.label2.TextAlign = global::System.Drawing.ContentAlignment.TopRight;
			this.redBar.LargeChange = 8;
			this.redBar.Location = new global::System.Drawing.Point(55, 118);
			this.redBar.Maximum = 255;
			this.redBar.Name = "redBar";
			this.redBar.Size = new global::System.Drawing.Size(260, 45);
			this.redBar.TabIndex = 7;
			this.redBar.TickFrequency = 8;
			this.redBar.Value = 255;
			this.redBar.Scroll += new global::System.EventHandler(this.redBar_Scroll);
			this.greenBox.Location = new global::System.Drawing.Point(321, 172);
			global::System.Windows.Forms.NumericUpDown numericUpDown5 = this.greenBox;
			int[] array5 = new int[4];
			array5[0] = 255;
			numericUpDown5.Maximum = new decimal(array5);
			this.greenBox.Name = "greenBox";
			this.greenBox.Size = new global::System.Drawing.Size(45, 20);
			this.greenBox.TabIndex = 12;
			global::System.Windows.Forms.NumericUpDown numericUpDown6 = this.greenBox;
			int[] array6 = new int[4];
			array6[0] = 255;
			numericUpDown6.Value = new decimal(array6);
			this.greenBox.ValueChanged += new global::System.EventHandler(this.greenBox_ValueChanged);
			this.label3.AutoSize = true;
			this.label3.Location = new global::System.Drawing.Point(10, 174);
			this.label3.Name = "label3";
			this.label3.Size = new global::System.Drawing.Size(39, 13);
			this.label3.TabIndex = 11;
			this.label3.Text = "Green:";
			this.label3.TextAlign = global::System.Drawing.ContentAlignment.TopRight;
			this.greenBar.LargeChange = 8;
			this.greenBar.Location = new global::System.Drawing.Point(55, 169);
			this.greenBar.Maximum = 255;
			this.greenBar.Name = "greenBar";
			this.greenBar.Size = new global::System.Drawing.Size(260, 45);
			this.greenBar.TabIndex = 10;
			this.greenBar.TickFrequency = 8;
			this.greenBar.Value = 255;
			this.greenBar.Scroll += new global::System.EventHandler(this.greenBar_Scroll);
			this.blueBox.Location = new global::System.Drawing.Point(321, 223);
			global::System.Windows.Forms.NumericUpDown numericUpDown7 = this.blueBox;
			int[] array7 = new int[4];
			array7[0] = 255;
			numericUpDown7.Maximum = new decimal(array7);
			this.blueBox.Name = "blueBox";
			this.blueBox.Size = new global::System.Drawing.Size(45, 20);
			this.blueBox.TabIndex = 15;
			global::System.Windows.Forms.NumericUpDown numericUpDown8 = this.blueBox;
			int[] array8 = new int[4];
			array8[0] = 255;
			numericUpDown8.Value = new decimal(array8);
			this.blueBox.ValueChanged += new global::System.EventHandler(this.blueBox_ValueChanged);
			this.label4.AutoSize = true;
			this.label4.Location = new global::System.Drawing.Point(19, 225);
			this.label4.Name = "label4";
			this.label4.Size = new global::System.Drawing.Size(31, 13);
			this.label4.TabIndex = 14;
			this.label4.Text = "Blue:";
			this.label4.TextAlign = global::System.Drawing.ContentAlignment.TopRight;
			this.blueBar.LargeChange = 8;
			this.blueBar.Location = new global::System.Drawing.Point(55, 220);
			this.blueBar.Maximum = 255;
			this.blueBar.Name = "blueBar";
			this.blueBar.Size = new global::System.Drawing.Size(260, 45);
			this.blueBar.TabIndex = 13;
			this.blueBar.TickFrequency = 8;
			this.blueBar.Value = 255;
			this.blueBar.ValueChanged += new global::System.EventHandler(this.blueBar_Scroll);
			this.label5.AutoSize = true;
			this.label5.Location = new global::System.Drawing.Point(12, 327);
			this.label5.Name = "label5";
			this.label5.Size = new global::System.Drawing.Size(71, 13);
			this.label5.TabIndex = 16;
			this.label5.Text = "Hexadecimal:";
			this.hexBox.Location = new global::System.Drawing.Point(89, 324);
			this.hexBox.Name = "hexBox";
			this.hexBox.Size = new global::System.Drawing.Size(60, 20);
			this.hexBox.TabIndex = 17;
			this.hexBox.TextChanged += new global::System.EventHandler(this.hexBox_TextChanged);
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(378, 357);
			base.Controls.Add(this.hexBox);
			base.Controls.Add(this.label5);
			base.Controls.Add(this.blueBox);
			base.Controls.Add(this.label4);
			base.Controls.Add(this.blueBar);
			base.Controls.Add(this.greenBox);
			base.Controls.Add(this.label3);
			base.Controls.Add(this.greenBar);
			base.Controls.Add(this.redBox);
			base.Controls.Add(this.label2);
			base.Controls.Add(this.redBar);
			base.Controls.Add(this.cancelButton);
			base.Controls.Add(this.newPreviewBox);
			base.Controls.Add(this.origPreviewBox);
			base.Controls.Add(this.alphaBox);
			base.Controls.Add(this.saveButton);
			base.Controls.Add(this.label1);
			base.Controls.Add(this.alphaBar);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "ColorEditDialog";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Edit Color";
			((global::System.ComponentModel.ISupportInitialize)this.alphaBar).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.alphaBox).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.newPreviewBox).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.origPreviewBox).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.redBox).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.redBar).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.greenBox).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.greenBar).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.blueBox).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.blueBar).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}
		private global::System.ComponentModel.IContainer components;
		private global::System.Windows.Forms.TrackBar alphaBar;
		private global::System.Windows.Forms.Label label1;
		private global::System.Windows.Forms.Button saveButton;
		private global::System.Windows.Forms.NumericUpDown alphaBox;
		private global::System.Windows.Forms.PictureBox origPreviewBox;
		private global::System.Windows.Forms.PictureBox newPreviewBox;
		private global::System.Windows.Forms.Button cancelButton;
		private global::System.Windows.Forms.NumericUpDown redBox;
		private global::System.Windows.Forms.Label label2;
		private global::System.Windows.Forms.TrackBar redBar;
		private global::System.Windows.Forms.NumericUpDown greenBox;
		private global::System.Windows.Forms.Label label3;
		private global::System.Windows.Forms.TrackBar greenBar;
		private global::System.Windows.Forms.NumericUpDown blueBox;
		private global::System.Windows.Forms.Label label4;
		private global::System.Windows.Forms.TrackBar blueBar;
		private global::System.Windows.Forms.Label label5;
		private global::System.Windows.Forms.TextBox hexBox;
	}
}
