namespace Spriteman
{
	public partial class SpriteEditDialog : global::System.Windows.Forms.Form
	{
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.okButton = new global::System.Windows.Forms.Button();
			this.cancelButton = new global::System.Windows.Forms.Button();
			this.label4 = new global::System.Windows.Forms.Label();
			this.originBox = new global::System.Windows.Forms.TextBox();
			this.label3 = new global::System.Windows.Forms.Label();
			this.boundsBox = new global::System.Windows.Forms.TextBox();
			this.label2 = new global::System.Windows.Forms.Label();
			this.coordsBox = new global::System.Windows.Forms.TextBox();
			this.nameBox = new global::System.Windows.Forms.TextBox();
			this.label1 = new global::System.Windows.Forms.Label();
			this.framesBox = new global::System.Windows.Forms.TextBox();
			this.label5 = new global::System.Windows.Forms.Label();
			this.speedBox = new global::System.Windows.Forms.TextBox();
			this.label6 = new global::System.Windows.Forms.Label();
			this.flipXBox = new global::System.Windows.Forms.CheckBox();
			this.flipYBox = new global::System.Windows.Forms.CheckBox();
			this.previewBox = new global::System.Windows.Forms.PictureBox();
			this.frameTimer = new global::System.Windows.Forms.Timer(this.components);
			this.animateButton = new global::System.Windows.Forms.Button();
			this.modeBox = new global::System.Windows.Forms.ComboBox();
			this.label7 = new global::System.Windows.Forms.Label();
			this.stepButton = new global::System.Windows.Forms.Button();
			this.extrasMenu = new global::System.Windows.Forms.ContextMenuStrip(this.components);
			this.showGuidesItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.showShadowItem = new global::System.Windows.Forms.ToolStripMenuItem();
			((global::System.ComponentModel.ISupportInitialize)this.previewBox).BeginInit();
			this.extrasMenu.SuspendLayout();
			base.SuspendLayout();
			this.okButton.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.okButton.Location = new global::System.Drawing.Point(256, 235);
			this.okButton.Name = "okButton";
			this.okButton.Size = new global::System.Drawing.Size(55, 23);
			this.okButton.TabIndex = 9;
			this.okButton.Text = "Save";
			this.okButton.UseVisualStyleBackColor = true;
			this.okButton.Click += new global::System.EventHandler(this.okButton_Click);
			this.cancelButton.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.cancelButton.Location = new global::System.Drawing.Point(317, 235);
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.Size = new global::System.Drawing.Size(55, 23);
			this.cancelButton.TabIndex = 10;
			this.cancelButton.Text = "Cancel";
			this.cancelButton.UseVisualStyleBackColor = true;
			this.cancelButton.Click += new global::System.EventHandler(this.cancelButton_Click);
			this.label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.label4.AutoSize = true;
			this.label4.Location = new global::System.Drawing.Point(16, 207);
			this.label4.Name = "label4";
			this.label4.Size = new global::System.Drawing.Size(37, 13);
			this.label4.TabIndex = 7;
			this.label4.Text = "Origin:";
			this.originBox.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.originBox.Location = new global::System.Drawing.Point(59, 204);
			this.originBox.Name = "originBox";
			this.originBox.Size = new global::System.Drawing.Size(100, 20);
			this.originBox.TabIndex = 4;
			this.originBox.TextChanged += new global::System.EventHandler(this.tbBounds_TextChanged);
			this.label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.label3.AutoSize = true;
			this.label3.Location = new global::System.Drawing.Point(7, 181);
			this.label3.Name = "label3";
			this.label3.Size = new global::System.Drawing.Size(46, 13);
			this.label3.TabIndex = 5;
			this.label3.Text = "Bounds:";
			this.boundsBox.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.boundsBox.Location = new global::System.Drawing.Point(59, 178);
			this.boundsBox.Name = "boundsBox";
			this.boundsBox.Size = new global::System.Drawing.Size(100, 20);
			this.boundsBox.TabIndex = 3;
			this.boundsBox.TextChanged += new global::System.EventHandler(this.tbBounds_TextChanged);
			this.label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.label2.AutoSize = true;
			this.label2.Location = new global::System.Drawing.Point(10, 155);
			this.label2.Name = "label2";
			this.label2.Size = new global::System.Drawing.Size(43, 13);
			this.label2.TabIndex = 3;
			this.label2.Text = "Coords:";
			this.coordsBox.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.coordsBox.Location = new global::System.Drawing.Point(59, 152);
			this.coordsBox.Name = "coordsBox";
			this.coordsBox.Size = new global::System.Drawing.Size(100, 20);
			this.coordsBox.TabIndex = 2;
			this.coordsBox.TextChanged += new global::System.EventHandler(this.tbBounds_TextChanged);
			this.nameBox.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.nameBox.Location = new global::System.Drawing.Point(59, 126);
			this.nameBox.Name = "nameBox";
			this.nameBox.Size = new global::System.Drawing.Size(100, 20);
			this.nameBox.TabIndex = 1;
			this.nameBox.TextChanged += new global::System.EventHandler(this.nameBox_TextChanged);
			this.label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.label1.AutoSize = true;
			this.label1.Location = new global::System.Drawing.Point(15, 129);
			this.label1.Name = "label1";
			this.label1.Size = new global::System.Drawing.Size(38, 13);
			this.label1.TabIndex = 0;
			this.label1.Text = "Name:";
			this.framesBox.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.framesBox.Location = new global::System.Drawing.Point(256, 126);
			this.framesBox.Name = "framesBox";
			this.framesBox.Size = new global::System.Drawing.Size(100, 20);
			this.framesBox.TabIndex = 5;
			this.framesBox.TextChanged += new global::System.EventHandler(this.tbFrames_TextChanged);
			this.label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.label5.AutoSize = true;
			this.label5.Location = new global::System.Drawing.Point(206, 129);
			this.label5.Name = "label5";
			this.label5.Size = new global::System.Drawing.Size(44, 13);
			this.label5.TabIndex = 11;
			this.label5.Text = "Frames:";
			this.speedBox.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.speedBox.Location = new global::System.Drawing.Point(256, 152);
			this.speedBox.Name = "speedBox";
			this.speedBox.Size = new global::System.Drawing.Size(100, 20);
			this.speedBox.TabIndex = 6;
			this.speedBox.TextChanged += new global::System.EventHandler(this.tbSpeed_TextChanged);
			this.label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.label6.AutoSize = true;
			this.label6.Location = new global::System.Drawing.Point(209, 155);
			this.label6.Name = "label6";
			this.label6.Size = new global::System.Drawing.Size(41, 13);
			this.label6.TabIndex = 13;
			this.label6.Text = "Speed:";
			this.flipXBox.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.flipXBox.AutoSize = true;
			this.flipXBox.CheckAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.flipXBox.Location = new global::System.Drawing.Point(215, 206);
			this.flipXBox.Name = "flipXBox";
			this.flipXBox.Size = new global::System.Drawing.Size(55, 17);
			this.flipXBox.TabIndex = 7;
			this.flipXBox.Text = "Flip X:";
			this.flipXBox.UseVisualStyleBackColor = true;
			this.flipXBox.CheckedChanged += new global::System.EventHandler(this.flipXBox_CheckedChanged);
			this.flipYBox.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.flipYBox.AutoSize = true;
			this.flipYBox.CheckAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.flipYBox.Location = new global::System.Drawing.Point(301, 206);
			this.flipYBox.Name = "flipYBox";
			this.flipYBox.Size = new global::System.Drawing.Size(55, 17);
			this.flipYBox.TabIndex = 8;
			this.flipYBox.Text = "Flip Y:";
			this.flipYBox.UseVisualStyleBackColor = true;
			this.flipYBox.CheckedChanged += new global::System.EventHandler(this.flipYBox_CheckedChanged);
			this.previewBox.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.previewBox.BackColor = global::System.Drawing.Color.White;
			this.previewBox.BackgroundImage = global::Spriteman.Properties.Resources.check;
			this.previewBox.ContextMenuStrip = this.extrasMenu;
			this.previewBox.Location = new global::System.Drawing.Point(0, 0);
			this.previewBox.Name = "previewBox";
			this.previewBox.Size = new global::System.Drawing.Size(384, 120);
			this.previewBox.TabIndex = 0;
			this.previewBox.TabStop = false;
			this.previewBox.Paint += new global::System.Windows.Forms.PaintEventHandler(this.previewBox_Paint);
			this.frameTimer.Tick += new global::System.EventHandler(this.frameTimer_Tick);
			this.animateButton.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.animateButton.Location = new global::System.Drawing.Point(12, 235);
			this.animateButton.Name = "animateButton";
			this.animateButton.Size = new global::System.Drawing.Size(55, 23);
			this.animateButton.TabIndex = 14;
			this.animateButton.Text = "Animate";
			this.animateButton.UseVisualStyleBackColor = true;
			this.animateButton.Click += new global::System.EventHandler(this.animateButton_Click);
			this.modeBox.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.modeBox.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.modeBox.FormattingEnabled = true;
			this.modeBox.Items.AddRange(new object[]
			{
				"Continuous",
				"1-2-1-3"
			});
			this.modeBox.Location = new global::System.Drawing.Point(256, 178);
			this.modeBox.Name = "modeBox";
			this.modeBox.Size = new global::System.Drawing.Size(100, 21);
			this.modeBox.TabIndex = 15;
			this.modeBox.SelectedIndexChanged += new global::System.EventHandler(this.modeBox_SelectedIndexChanged);
			this.label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.label7.AutoSize = true;
			this.label7.Location = new global::System.Drawing.Point(213, 182);
			this.label7.Name = "label7";
			this.label7.Size = new global::System.Drawing.Size(37, 13);
			this.label7.TabIndex = 16;
			this.label7.Text = "Mode:";
			this.stepButton.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.stepButton.Location = new global::System.Drawing.Point(73, 235);
			this.stepButton.Name = "stepButton";
			this.stepButton.Size = new global::System.Drawing.Size(40, 23);
			this.stepButton.TabIndex = 17;
			this.stepButton.Text = "Step";
			this.stepButton.UseVisualStyleBackColor = true;
			this.stepButton.Click += new global::System.EventHandler(this.stepButton_Click);
			this.extrasMenu.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.showGuidesItem,
				this.showShadowItem
			});
			this.extrasMenu.Name = "extrasMenu";
			this.extrasMenu.Size = new global::System.Drawing.Size(153, 70);
			this.showGuidesItem.Name = "showGuidesItem";
			this.showGuidesItem.Size = new global::System.Drawing.Size(152, 22);
			this.showGuidesItem.Text = "Show Guides";
			this.showGuidesItem.Click += new global::System.EventHandler(this.showGuidesItem_Click);
			this.showShadowItem.Name = "showShadowItem";
			this.showShadowItem.Size = new global::System.Drawing.Size(152, 22);
			this.showShadowItem.Text = "Show Shadow";
			this.showShadowItem.Click += new global::System.EventHandler(this.showShadowItem_Click);
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(384, 261);
			base.Controls.Add(this.stepButton);
			base.Controls.Add(this.label7);
			base.Controls.Add(this.modeBox);
			base.Controls.Add(this.animateButton);
			base.Controls.Add(this.flipYBox);
			base.Controls.Add(this.flipXBox);
			base.Controls.Add(this.label6);
			base.Controls.Add(this.speedBox);
			base.Controls.Add(this.label5);
			base.Controls.Add(this.framesBox);
			base.Controls.Add(this.okButton);
			base.Controls.Add(this.cancelButton);
			base.Controls.Add(this.previewBox);
			base.Controls.Add(this.label4);
			base.Controls.Add(this.label1);
			base.Controls.Add(this.originBox);
			base.Controls.Add(this.nameBox);
			base.Controls.Add(this.label3);
			base.Controls.Add(this.coordsBox);
			base.Controls.Add(this.boundsBox);
			base.Controls.Add(this.label2);
			base.MaximizeBox = false;
			this.MaximumSize = new global::System.Drawing.Size(600, 480);
			base.MinimizeBox = false;
			this.MinimumSize = new global::System.Drawing.Size(400, 300);
			base.Name = "SpriteEditDialog";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Edit Sprite";
			base.Load += new global::System.EventHandler(this.SpriteEditDialog_Load);
			((global::System.ComponentModel.ISupportInitialize)this.previewBox).EndInit();
			this.extrasMenu.ResumeLayout(false);
			base.ResumeLayout(false);
			base.PerformLayout();
		}
		private global::System.ComponentModel.IContainer components;
		private global::System.Windows.Forms.PictureBox previewBox;
		private global::System.Windows.Forms.TextBox nameBox;
		private global::System.Windows.Forms.Label label1;
		private global::System.Windows.Forms.Button okButton;
		private global::System.Windows.Forms.Button cancelButton;
		private global::System.Windows.Forms.Label label4;
		private global::System.Windows.Forms.TextBox originBox;
		private global::System.Windows.Forms.Label label3;
		private global::System.Windows.Forms.TextBox boundsBox;
		private global::System.Windows.Forms.Label label2;
		private global::System.Windows.Forms.TextBox coordsBox;
		private global::System.Windows.Forms.TextBox framesBox;
		private global::System.Windows.Forms.Label label5;
		private global::System.Windows.Forms.TextBox speedBox;
		private global::System.Windows.Forms.Label label6;
		private global::System.Windows.Forms.CheckBox flipXBox;
		private global::System.Windows.Forms.CheckBox flipYBox;
		private global::System.Windows.Forms.Timer frameTimer;
		private global::System.Windows.Forms.Button animateButton;
		private global::System.Windows.Forms.ComboBox modeBox;
		private global::System.Windows.Forms.Label label7;
		private global::System.Windows.Forms.Button stepButton;
		private global::System.Windows.Forms.ContextMenuStrip extrasMenu;
		private global::System.Windows.Forms.ToolStripMenuItem showGuidesItem;
		private global::System.Windows.Forms.ToolStripMenuItem showShadowItem;
	}
}
